DROP DATABASE IF EXISTS GREATBAY_DB;
CREATE DATABASE GREATBAY_DB;

USE GREATBAY_DB;

CREATE TABLE AUCTION(
  ID INT NOT NULL AUTO_INCREMENT,
  ITEM_NAME VARCHAR(100) NOT NULL,
  CATEGORY VARCHAR(45) NOT NULL,
  STARTING_BID INT DEFAULT 0,
  HIGHEST_BID INT DEFAULT 0,
  PRIMARY KEY (ID)
);